import { NextRequest, NextResponse } from 'next/server';
import { supabaseServer } from '@/lib/supabaseServer';
import { google } from 'googleapis';

export async function POST(req: NextRequest) {
  try {
    const { sessionId } = await req.json();

    // TODO: Get actual user_id from auth session
    const userId = req.headers.get('x-user-id') || '00000000-0000-0000-0000-000000000000';

    // Get session data
    const { data: session } = await supabaseServer
      .from('study_sessions')
      .select('*')
      .eq('id', sessionId)
      .single();

    if (!session) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 });
    }

    // Generate summary content
    const content = `# Study Session Summary

**Topic:** ${session.topic}
**Date:** ${new Date(session.created_at).toLocaleDateString('sv-SE')}
**Duration:** ${session.duration || 'N/A'} minutes
**Understanding Score:** ${session.understanding_score || 'N/A'}/5

## Reflection

${session.reflection || 'No reflection provided'}

## Key Takeaways

${session.key_takeaways || 'None recorded'}

## Next Steps

${session.next_steps || 'To be determined'}

---

*Generated by Study OS*
`;

    // Get Google tokens
    const { data: calendar } = await supabaseServer
      .from('user_calendars')
      .select('*')
      .eq('user_id', userId)
      .single();

    if (!calendar) {
      return NextResponse.json({ error: 'Google not connected' }, { status: 400 });
    }

    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI || `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/api/auth/google/callback`
    );

    oauth2Client.setCredentials({
      access_token: calendar.google_access_token,
      refresh_token: calendar.google_refresh_token,
    });

    const docs = google.docs({ version: 'v1', auth: oauth2Client });
    const drive = google.drive({ version: 'v3', auth: oauth2Client });

    // Create doc
    const doc = await docs.documents.create({
      requestBody: {
        title: `Study Session - ${session.topic} - ${new Date().toLocaleDateString()}`,
      },
    });

    // Insert content
    await docs.documents.batchUpdate({
      documentId: doc.data.documentId!,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: content,
            },
          },
        ],
      },
    });

    // Make shareable
    await drive.permissions.create({
      fileId: doc.data.documentId!,
      requestBody: {
        role: 'reader',
        type: 'anyone',
      },
    });

    const docUrl = `https://docs.google.com/document/d/${doc.data.documentId}`;

    // Save to DB
    await supabaseServer.from('notebooklm_exports').insert({
      user_id: userId,
      session_id: sessionId,
      doc_title: doc.data.title!,
      doc_url: docUrl,
      content,
      export_type: 'session_summary',
    });

    return NextResponse.json({
      success: true,
      docUrl,
      notebooklmUrl: `https://notebooklm.google.com?source=${encodeURIComponent(docUrl)}`,
    });
  } catch (error: any) {
    console.error('Doc creation error:', error);
    return NextResponse.json({ error: 'Failed to create document' }, { status: 500 });
  }
}

